"""initial

Revision ID: 2d75117ba1f8
Revises: 
Create Date: 2021-01-03 15:42:37.556205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d75117ba1f8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('context_features',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('name'),
    sa.UniqueConstraint('index')
    )
    op.create_table('settings',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('default_value', sa.String(), nullable=True),
    sa.Column('last_touch_time', sa.TIMESTAMP(), nullable=False),
    sa.Column('metadata', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('configurable',
    sa.Column('setting', sa.String(), nullable=True),
    sa.Column('context_feature', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['context_feature'], ['context_features.name'], ),
    sa.ForeignKeyConstraint(['setting'], ['settings.name'], ondelete='CASCADE'),
    sa.UniqueConstraint('setting', 'context_feature')
    )
    op.create_index(op.f('ix_configurable_setting'), 'configurable', ['setting'], unique=False)
    op.create_table('rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('setting', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('metadata', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['setting'], ['settings.name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rules_setting'), 'rules', ['setting'], unique=False)
    op.create_table('conditions',
    sa.Column('rule', sa.Integer(), nullable=True),
    sa.Column('context_feature', sa.String(), nullable=True),
    sa.Column('feature_value', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['context_feature'], ['context_features.name'], ),
    sa.ForeignKeyConstraint(['rule'], ['rules.id'], ondelete='CASCADE'),
    sa.UniqueConstraint('rule', 'context_feature')
    )
    op.create_index(op.f('ix_conditions_rule'), 'conditions', ['rule'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conditions_rule'), table_name='conditions')
    op.drop_table('conditions')
    op.drop_index(op.f('ix_rules_setting'), table_name='rules')
    op.drop_table('rules')
    op.drop_index(op.f('ix_configurable_setting'), table_name='configurable')
    op.drop_table('configurable')
    op.drop_table('settings')
    op.drop_table('context_features')
    # ### end Alembic commands ###
