""""added setting versioning + default is now required"

Revision ID: 83f0f272313f
Revises: 7713520cb02b
Create Date: 2022-01-04 14:04:46.416415

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '83f0f272313f'
down_revision = '7713520cb02b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conditions', 'rule',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column('conditions', 'context_feature',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.alter_column('configurable', 'setting',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.alter_column('configurable', 'context_feature',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.alter_column('rule_metadata', 'rule',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column('rules', 'setting',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.alter_column('setting_aliases', 'setting',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.alter_column('setting_metadata', 'setting',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.add_column('settings', sa.Column('version', sa.String(), nullable=True))
    op.execute("UPDATE settings SET version = '1.0'")
    op.alter_column('settings', 'default_value',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.alter_column('settings', 'default_value',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('settings', 'default_value',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.drop_column('settings', 'version')
    op.alter_column('setting_metadata', 'setting',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.alter_column('setting_aliases', 'setting',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.alter_column('rules', 'setting',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.alter_column('rule_metadata', 'rule',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('configurable', 'context_feature',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.alter_column('configurable', 'setting',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.alter_column('conditions', 'context_feature',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.alter_column('conditions', 'rule',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    # ### end Alembic commands ###
